name: VocalApp_AudioRecorder
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  avatar_glow: ^2.0.1

  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter

  # record and play audio
  flutter_sound_lite: ^8.1.9

  # file permissions
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
